import {
  Tenant,
  UserProfile,
  Specialty,
  Professional,
  Room,
  Procedure,
  HealthInsurance,
  Patient,
  Appointment,
  PhysicalEvaluation,
  Evolution,
  Prescription,
  PatientConsentTerm,
  Package,
  PatientPackagePurchase,
  Account,
  CostCenter,
  FinancialCategory,
  PaymentMethod,
  FinancialEntry,
  Product,
  ProductCategory,
  UnitOfMeasure,
  Supplier,
  Equipment,
  TechnicalAssistance,
  InternalMessage,
  LicenseKey,
  AuditLog,
} from '../types';

export const INITIAL_TENANTS: Tenant[] = [
  {
    id: 'tenant-1',
    name: 'FisioPilates Integrada - Clínica São Paulo',
    tradeName: 'FisioPilates SP',
    cnpj: '12.345.678/0001-90',
    email: 'contato@fisiopilatessp.com.br',
    phone: '(11) 3456-7890',
    address: 'Av. Paulista, 1500 - Conjunto 802 - Bela Vista',
    city: 'São Paulo',
    state: 'SP',
    slug: 'fisiopilates-sp',
    primaryColor: '#0d9488', // Teal
    planId: 'equipe',
    financialManagerActive: true,
    additionalProfessionalsCount: 1,
    trialEndsAt: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString(),
    isTrialActive: false,
    subscriptionStatus: 'active',
    welcomeMessage: 'Bem-vindo(a) à FisioPilates Integrada São Paulo!',
    createdAt: '2025-01-10T10:00:00Z',
  },
  {
    id: 'tenant-2',
    name: 'Clínica Estética & Bem-Estar BellaCorpo',
    tradeName: 'BellaCorpo Estética',
    cnpj: '98.765.432/0001-10',
    email: 'adm@bellacorpo.com.br',
    phone: '(21) 2555-1234',
    address: 'Rua Visconde de Pirajá, 350 - Ipanema',
    city: 'Rio de Janeiro',
    state: 'RJ',
    slug: 'bellacorpo',
    primaryColor: '#e11d48', // Rose
    planId: 'clinica',
    financialManagerActive: true,
    additionalProfessionalsCount: 3,
    trialEndsAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    isTrialActive: false,
    subscriptionStatus: 'active',
    welcomeMessage: 'Bem-vindo(a) à Clínica BellaCorpo Estética & Saúde!',
    createdAt: '2025-02-01T14:30:00Z',
  },
  {
    id: 'tenant-3',
    name: 'Movimento & Reabilitação Funcional',
    tradeName: 'Movimento Fisioterapia',
    cnpj: '45.123.890/0001-55',
    email: 'contato@movimentofisio.com.br',
    phone: '(31) 3222-4455',
    address: 'Rua Fernandes Tourinho, 200 - Savassi',
    city: 'Belo Horizonte',
    state: 'MG',
    slug: 'movimento-fisio',
    primaryColor: '#2563eb', // Blue
    planId: 'profissional',
    financialManagerActive: false,
    additionalProfessionalsCount: 0,
    trialEndsAt: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    isTrialActive: true,
    subscriptionStatus: 'trial',
    welcomeMessage: 'Bem-vindo(a) à Movimento Fisioterapia e Reabilitação!',
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'user-superadmin',
    tenantId: 'tenant-1',
    name: 'SuperAdmin Master',
    email: 'superadmin@clinicflow.com.br',
    role: 'superadmin',
    phone: '(11) 99999-0000',
    cpf: '000.000.000-00',
    status: 'active',
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'user-admin-1',
    tenantId: 'tenant-1',
    name: 'Dra. Helena Ribeiro (Gestora)',
    email: 'helena@fisiopilatessp.com.br',
    role: 'admin',
    phone: '(11) 98888-1111',
    cpf: '123.456.789-01',
    status: 'active',
    createdAt: '2025-01-10T10:00:00Z',
  },
  {
    id: 'user-prof-1',
    tenantId: 'tenant-1',
    name: 'Dra. Carolina Castro',
    email: 'carolina.fisio@fisiopilatessp.com.br',
    role: 'professional',
    professionalId: 'prof-1',
    phone: '(11) 97777-2222',
    cpf: '234.567.890-12',
    status: 'active',
    createdAt: '2025-01-10T10:00:00Z',
  },
  {
    id: 'user-sec-1',
    tenantId: 'tenant-1',
    name: 'Mariana Duarte (Recepção)',
    email: 'recepcao@fisiopilatessp.com.br',
    role: 'secretary',
    phone: '(11) 96666-3333',
    cpf: '345.678.901-23',
    status: 'active',
    createdAt: '2025-01-10T10:00:00Z',
  },
  {
    id: 'user-patient-1',
    tenantId: 'tenant-1',
    name: 'Lucas Mendes de Almeida',
    email: 'lucas.mendes@gmail.com',
    role: 'patient',
    patientId: 'patient-1',
    phone: '(11) 95555-4444',
    cpf: '456.789.012-34',
    status: 'active',
    createdAt: '2025-01-15T11:00:00Z',
  },
];

export const INITIAL_SPECIALTIES: Specialty[] = [
  {
    id: 'spec-1',
    tenantId: 'tenant-1',
    name: 'Fisioterapia Traumato-Ortopédica',
    description: 'Reabilitação pós-cirúrgica, dores na coluna, lesões articulares e musculares',
    color: '#0d9488',
    active: true,
  },
  {
    id: 'spec-2',
    tenantId: 'tenant-1',
    name: 'Pilates Clínico & Funcional',
    description: 'Fortalecimento de core, alinhamento postural e condicionamento físico',
    color: '#0284c7',
    active: true,
  },
  {
    id: 'spec-3',
    tenantId: 'tenant-1',
    name: 'Fisioterapia Pélvica & Saúde da Mulher',
    description: 'Preparação para o parto, pós-parto e disfunções uroginecológicas',
    color: '#ec4899',
    active: true,
  },
  {
    id: 'spec-4',
    tenantId: 'tenant-1',
    name: 'Osteopatia & Terapia Manual',
    description: 'Manipulações articulares e alívio de bloqueios e dores crônicas',
    color: '#8b5cf6',
    active: true,
  },
  {
    id: 'spec-5',
    tenantId: 'tenant-2',
    name: 'Estética Facial e Corporal Avançada',
    description: 'Drenagem linfática, pós-operatório cirúrgico, limpeza de pele e peeling',
    color: '#e11d48',
    active: true,
  },
];

export const INITIAL_PROFESSIONALS: Professional[] = [
  {
    id: 'prof-1',
    tenantId: 'tenant-1',
    name: 'Dra. Carolina Castro',
    email: 'carolina.fisio@fisiopilatessp.com.br',
    phone: '(11) 97777-2222',
    councilRegistration: 'CREFITO-3/294819-F',
    specialtyIds: ['spec-1', 'spec-2'],
    commissionPercent: 50.0,
    pixKey: 'carolina.fisio@gmail.com',
    bankName: 'Banco Itaú',
    bankAgency: '1234',
    bankAccount: '98765-4',
    color: '#0d9488',
    googleCalendarConnected: true,
    googleCalendarEmail: 'carolina.fisio@gmail.com',
    active: true,
  },
  {
    id: 'prof-2',
    tenantId: 'tenant-1',
    name: 'Dr. Thiago Medeiros',
    email: 'thiago.osteopatia@fisiopilatessp.com.br',
    phone: '(11) 97111-3344',
    councilRegistration: 'CREFITO-3/184200-F',
    specialtyIds: ['spec-1', 'spec-4'],
    commissionPercent: 60.0,
    pixKey: '11971113344',
    bankName: 'Nubank',
    bankAgency: '0001',
    bankAccount: '1234567-8',
    color: '#8b5cf6',
    googleCalendarConnected: false,
    active: true,
  },
  {
    id: 'prof-3',
    tenantId: 'tenant-1',
    name: 'Dra. Juliana Vasconcelos',
    email: 'juliana.pelvica@fisiopilatessp.com.br',
    phone: '(11) 97222-5566',
    councilRegistration: 'CREFITO-3/310492-F',
    specialtyIds: ['spec-3', 'spec-2'],
    commissionPercent: 55.0,
    pixKey: 'juliana.pelvica@gmail.com',
    bankName: 'Banco Bradesco',
    bankAgency: '3456',
    bankAccount: '55443-2',
    color: '#ec4899',
    googleCalendarConnected: true,
    googleCalendarEmail: 'juliana.pelvica@gmail.com',
    active: true,
  },
  {
    id: 'prof-4',
    tenantId: 'tenant-2',
    name: 'Dra. Gabriela Fontes',
    email: 'gabriela@bellacorpo.com.br',
    phone: '(21) 98899-7766',
    councilRegistration: 'CRBM-1/45890',
    specialtyIds: ['spec-5'],
    commissionPercent: 50.0,
    pixKey: 'gabriela.estetica@gmail.com',
    bankName: 'Santander',
    bankAgency: '0450',
    bankAccount: '13009944-1',
    color: '#e11d48',
    googleCalendarConnected: true,
    active: true,
  },
];

export const INITIAL_ROOMS: Room[] = [
  {
    id: 'room-1',
    tenantId: 'tenant-1',
    name: 'Studio Pilates - Sala Principal',
    capacity: 4,
    sector: 'Studio Pilates (Piso 2)',
    modalities: [
      'Pilates Clínico em Aparelhos',
      'Pilates Solo & Acessórios',
      'Reabilitação Postural Funcional',
      'Treinamento Proprioceptivo',
    ],
    status: 'in_use',
    currentOccupant: {
      patientName: 'Ana Beatriz Faria',
      patientId: 'pat-2',
      professionalName: 'Dra. Carolina Castro',
      professionalId: 'prof-1',
      procedureName: 'Pilates Clínico Individual / Dupla',
      modality: 'Pilates Clínico em Aparelhos',
      startedAt: '14:00',
      durationMinutes: 60,
      estimatedEndTime: '15:00',
    },
    equipmentIds: ['eq-1', 'eq-2'],
    inMaintenance: false,
    color: '#0d9488',
    active: true,
  },
  {
    id: 'room-2',
    tenantId: 'tenant-1',
    name: 'Consultório 01 - Fisioterapia & Eletroterapia',
    capacity: 1,
    sector: 'Ala Clínica Geral (Piso 1)',
    modalities: [
      'Fisioterapia Traumato-Ortopédica',
      'Eletroterapia & Termoterapia',
      'Reabilitação Esportiva & Cinesioterapia',
      'Liberação Miofascial Instrumental',
    ],
    status: 'available',
    equipmentIds: ['eq-3', 'eq-4'],
    inMaintenance: false,
    color: '#2563eb',
    active: true,
  },
  {
    id: 'room-3',
    tenantId: 'tenant-1',
    name: 'Consultório 02 - Terapia Manual & Osteopatia',
    capacity: 1,
    sector: 'Ala Clínica Geral (Piso 1)',
    modalities: [
      'Osteopatia Estrutural & Visceral',
      'Terapia Manual Ortopédica',
      'Dry Needling (Agulhamento a Seco)',
      'RPG (Reeducação Postural Global)',
    ],
    status: 'in_use',
    currentOccupant: {
      patientName: 'Carlos Alberto Moreira',
      patientId: 'pat-1',
      professionalName: 'Dr. Thiago Medeiros',
      professionalId: 'prof-2',
      procedureName: 'Sessão de Osteopatia e Liberação Miofascial',
      modality: 'Osteopatia Estrutural & Visceral',
      startedAt: '14:15',
      durationMinutes: 50,
      estimatedEndTime: '15:05',
    },
    equipmentIds: [],
    inMaintenance: false,
    color: '#8b5cf6',
    active: true,
  },
  {
    id: 'room-4',
    tenantId: 'tenant-1',
    name: 'Sala 03 - Fisioterapia Pélvica & Biofeedback',
    capacity: 1,
    sector: 'Ala Especializada (Piso 1)',
    modalities: [
      'Fisioterapia Pélvica & Uroginecológica',
      'Biofeedback Eletromiográfico',
      'Tratamento de Disfunções do Assoalho Pélvico',
      'Preparação para o Parto',
    ],
    status: 'cleaning',
    equipmentIds: [],
    inMaintenance: false,
    color: '#ec4899',
    active: true,
  },
  {
    id: 'room-5',
    tenantId: 'tenant-1',
    name: 'Consultório 04 - Estética Avançada & Drenagem',
    capacity: 1,
    sector: 'Ala Estética (Piso 2)',
    modalities: [
      'Drenagem Linfática Pós-Operatória',
      'Radiofrequência & Ultrassom',
      'Limpeza de Pele Profunda',
      'Massoterapia Relaxante',
    ],
    status: 'maintenance',
    inMaintenance: true,
    maintenanceNote: 'Higienização e calibração de sensor do ultrassom prevista até 05/09',
    equipmentIds: [],
    color: '#f59e0b',
    active: true,
  },
  {
    id: 'room-6',
    tenantId: 'tenant-2',
    name: 'Box 01 - Fisioterapia Rápida',
    capacity: 1,
    sector: 'Box Individual',
    modalities: ['Fisioterapia Traumato-Ortopédica', 'Cinesioterapia'],
    status: 'available',
    equipmentIds: [],
    inMaintenance: false,
    color: '#10b981',
    active: true,
  },
];

export const INITIAL_CLINIC_TASKS = [
  {
    id: 'task-1',
    tenantId: 'tenant-1',
    title: 'Confirmar pacientes agendados para amanhã via WhatsApp',
    category: 'reception' as const,
    priority: 'high' as const,
    completed: false,
    dueDate: new Date().toISOString().split('T')[0],
    assignedRole: 'secretary' as const,
    assignedUserName: 'Mariana (Recepção)',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task-2',
    tenantId: 'tenant-1',
    title: 'Enviar guias TISS pendentes para operadora Unimed',
    category: 'financial' as const,
    priority: 'urgent' as const,
    completed: false,
    dueDate: new Date().toISOString().split('T')[0],
    assignedRole: 'admin' as const,
    assignedUserName: 'Dra. Helena (Gestora)',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task-3',
    tenantId: 'tenant-1',
    title: 'Higienização e reposição de lençóis no Studio de Pilates',
    category: 'sanitation' as const,
    priority: 'medium' as const,
    completed: true,
    dueDate: new Date().toISOString().split('T')[0],
    assignedRole: 'all' as const,
    assignedUserName: 'Equipe de Apoio',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task-4',
    tenantId: 'tenant-1',
    title: 'Preencher evolução clínica do paciente Marcos Silva (Sessão 10)',
    category: 'clinical' as const,
    priority: 'high' as const,
    completed: false,
    dueDate: new Date().toISOString().split('T')[0],
    assignedRole: 'professional' as const,
    assignedUserName: 'Dra. Carolina Castro',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'task-5',
    tenantId: 'tenant-1',
    title: 'Conferir fechamento diário do caixa físico e PIX recebidos',
    category: 'financial' as const,
    priority: 'medium' as const,
    completed: false,
    dueDate: new Date().toISOString().split('T')[0],
    assignedRole: 'secretary' as const,
    assignedUserName: 'Mariana (Recepção)',
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_PROCEDURES: Procedure[] = [
  {
    id: 'proc-1',
    tenantId: 'tenant-1',
    name: 'Sessão de Fisioterapia Ortopédica / Reabilitação',
    specialtyId: 'spec-1',
    durationMinutes: 50,
    price: 160.0,
    description: 'Avaliação contínua, cinesioterapia, eletroterapia e recursos analgésicos',
    active: true,
  },
  {
    id: 'proc-2',
    tenantId: 'tenant-1',
    name: 'Pilates Clínico Individual / Dupla',
    specialtyId: 'spec-2',
    durationMinutes: 60,
    price: 130.0,
    description: 'Atendimento no Studio completo com aparelhos Reformer, Cadillac e Chair',
    active: true,
  },
  {
    id: 'proc-3',
    tenantId: 'tenant-1',
    name: 'Consulta e Avaliação de Fisioterapia Pélvica',
    specialtyId: 'spec-3',
    durationMinutes: 60,
    price: 220.0,
    description: 'Avaliação funcional do assoalho pélvico e plano de conduta terapêutica',
    active: true,
  },
  {
    id: 'proc-4',
    tenantId: 'tenant-1',
    name: 'Sessão de Osteopatia e Liberação Miofascial',
    specialtyId: 'spec-4',
    durationMinutes: 50,
    price: 200.0,
    description: 'Manipulações globais articulares, viscerais e cranianas para alívio de dor',
    active: true,
  },
];

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'patient-1',
    tenantId: 'tenant-1',
    name: 'Lucas Mendes de Almeida',
    cpf: '456.789.012-34',
    birthDate: '1989-06-14',
    gender: 'M',
    email: 'lucas.mendes@gmail.com',
    phone: '(11) 95555-4444',
    whatsapp: '5511955554444',
    address: 'Rua Bela Cintra, 890 - Consolação',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '01415-000',
    emergencyContactName: 'Fernanda Mendes (Esposa)',
    emergencyContactPhone: '(11) 95555-8888',
    healthInsurance: 'Bradesco Saúde Top Nacional',
    healthInsuranceNumber: '78912345600',
    allergies: ['Dipirona', 'Iodo'],
    medicalHistory: 'Pós-operatório de LCA joelho direito (há 3 meses). Hérnia discal L5-S1 assintomática.',
    currentMedications: 'Nenhum uso contínuo.',
    notes: 'Paciente atleta amador de corrida. Foco em retorno seguro aos treinos.',
    packageId: 'pkg-1',
    active: true,
    createdAt: '2025-01-15T11:00:00Z',
  },
  {
    id: 'patient-2',
    tenantId: 'tenant-1',
    name: 'Camila Rocha Nogueira',
    cpf: '321.654.987-11',
    birthDate: '1995-11-28',
    gender: 'F',
    email: 'camila.rocha@uol.com.br',
    phone: '(11) 94444-1212',
    whatsapp: '5511944441212',
    address: 'Alameda Santos, 1200 - Cerqueira César',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '01418-100',
    emergencyContactName: 'Roberto Nogueira (Pai)',
    emergencyContactPhone: '(11) 94444-9999',
    healthInsurance: 'SulAmérica Especial',
    healthInsuranceNumber: '45678901234',
    allergies: [],
    medicalHistory: 'Gestante de 28 semanas. Lombalgia gestacional e dor na sínfise púbica.',
    currentMedications: 'Polivitamínico pré-natal.',
    notes: 'Acompanhamento com Fisioterapia Pélvica e Pilates Gestacional.',
    packageId: 'pkg-2',
    active: true,
    createdAt: '2025-01-20T09:30:00Z',
  },
  {
    id: 'patient-3',
    tenantId: 'tenant-1',
    name: 'Antônio Carlos Silveira',
    cpf: '555.666.777-88',
    birthDate: '1962-03-05',
    gender: 'M',
    email: 'antonio.silveira@empresa.com.br',
    phone: '(11) 93333-8765',
    whatsapp: '5511933338765',
    address: 'Rua Pamplona, 450 - Jardim Paulista',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '01405-000',
    emergencyContactName: 'Beatriz Silveira (Filha)',
    emergencyContactPhone: '(11) 93333-1122',
    healthInsurance: 'Amil 500',
    healthInsuranceNumber: '9988776655',
    allergies: ['Penicilina'],
    medicalHistory: 'Tendinopatia do manguito rotador ombro esquerdo. Hipertensão arterial controlada.',
    currentMedications: 'Losartana 50mg.',
    notes: 'Encaminhado pelo Dr. Marcelo (Ortopedista).',
    active: true,
    createdAt: '2025-02-05T15:00:00Z',
  },
  {
    id: 'patient-4',
    tenantId: 'tenant-1',
    name: 'Juliana Paes de Barros',
    cpf: '888.999.000-11',
    birthDate: '1984-08-19',
    gender: 'F',
    email: 'juliana.barros@gmail.com',
    phone: '(11) 92222-3344',
    whatsapp: '5511922223344',
    address: 'Rua Oscar Freire, 700 - Pinheiros',
    city: 'São Paulo',
    state: 'SP',
    zipCode: '05409-011',
    emergencyContactName: 'Eduardo Barros (Irmão)',
    emergencyContactPhone: '(11) 92222-7788',
    healthInsurance: 'Particular',
    allergies: [],
    medicalHistory: 'Cervicobraquialgia e estresse postural (trabalho em home office).',
    notes: 'Faz Pilates 2x na semana há 6 meses.',
    packageId: 'pkg-1',
    active: true,
    createdAt: '2025-01-05T08:00:00Z',
  },
];

// Today and surrounding dates helper
const today = new Date();
const formatDate = (offsetDays: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split('T')[0];
};

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt-1',
    tenantId: 'tenant-1',
    patientId: 'patient-1',
    patientName: 'Lucas Mendes de Almeida',
    patientPhone: '(11) 95555-4444',
    professionalId: 'prof-1',
    professionalName: 'Dra. Carolina Castro',
    procedureId: 'proc-1',
    procedureName: 'Sessão de Fisioterapia Ortopédica / Reabilitação',
    specialtyId: 'spec-1',
    roomId: 'room-2',
    roomName: 'Consultório 01 - Fisioterapia & Eletroterapia',
    date: formatDate(0), // Today
    startTime: '09:00',
    endTime: '09:50',
    status: 'confirmed',
    notes: 'Treino de propriocepção e fortalecimento excêntrico de quadríceps.',
    syncedWithGoogle: true,
    whatsappReminderSent: true,
    price: 160.0,
  },
  {
    id: 'apt-2',
    tenantId: 'tenant-1',
    patientId: 'patient-2',
    patientName: 'Camila Rocha Nogueira',
    patientPhone: '(11) 94444-1212',
    professionalId: 'prof-3',
    professionalName: 'Dra. Juliana Vasconcelos',
    procedureId: 'proc-3',
    procedureName: 'Consulta e Avaliação de Fisioterapia Pélvica',
    specialtyId: 'spec-3',
    roomId: 'room-3',
    roomName: 'Consultório 02 - Terapia Manual & Osteopatia',
    date: formatDate(0), // Today
    startTime: '10:30',
    endTime: '11:30',
    status: 'confirmed',
    notes: 'Avaliação de mobilidade pélvica e exercícios respiratórios com Epi-no.',
    syncedWithGoogle: true,
    whatsappReminderSent: true,
    price: 220.0,
  },
  {
    id: 'apt-3',
    tenantId: 'tenant-1',
    patientId: 'patient-4',
    patientName: 'Juliana Paes de Barros',
    patientPhone: '(11) 92222-3344',
    professionalId: 'prof-1',
    professionalName: 'Dra. Carolina Castro',
    procedureId: 'proc-2',
    procedureName: 'Pilates Clínico Individual / Dupla',
    specialtyId: 'spec-2',
    roomId: 'room-1',
    roomName: 'Studio Pilates - Sala Principal',
    date: formatDate(0), // Today
    startTime: '14:00',
    endTime: '15:00',
    status: 'pending',
    notes: 'Paciente solicitou confirmação de horário.',
    syncedWithGoogle: false,
    whatsappReminderSent: false,
    price: 130.0,
  },
  {
    id: 'apt-4',
    tenantId: 'tenant-1',
    patientId: 'patient-3',
    patientName: 'Antônio Carlos Silveira',
    patientPhone: '(11) 93333-8765',
    professionalId: 'prof-2',
    professionalName: 'Dr. Thiago Medeiros',
    procedureId: 'proc-4',
    procedureName: 'Sessão de Osteopatia e Liberação Miofascial',
    specialtyId: 'spec-4',
    roomId: 'room-3',
    roomName: 'Consultório 02 - Terapia Manual & Osteopatia',
    date: formatDate(1), // Tomorrow
    startTime: '15:00',
    endTime: '15:50',
    status: 'confirmed',
    notes: 'Mobilização escapuloumeral e liberação de peitoral menor.',
    syncedWithGoogle: true,
    whatsappReminderSent: true,
    price: 200.0,
  },
  {
    id: 'apt-5',
    tenantId: 'tenant-1',
    patientId: 'patient-1',
    patientName: 'Lucas Mendes de Almeida',
    patientPhone: '(11) 95555-4444',
    professionalId: 'prof-1',
    professionalName: 'Dra. Carolina Castro',
    procedureId: 'proc-1',
    procedureName: 'Sessão de Fisioterapia Ortopédica / Reabilitação',
    specialtyId: 'spec-1',
    roomId: 'room-2',
    roomName: 'Consultório 01 - Fisioterapia & Eletroterapia',
    date: formatDate(-2), // 2 days ago
    startTime: '09:00',
    endTime: '09:50',
    status: 'completed',
    notes: 'Sessão concluída com sucesso. Ganho de ADM para 130º de flexão.',
    syncedWithGoogle: true,
    whatsappReminderSent: true,
    price: 160.0,
  },
];

export const INITIAL_PHYSICAL_EVALUATIONS: PhysicalEvaluation[] = [
  {
    id: 'eval-1',
    tenantId: 'tenant-1',
    patientId: 'patient-1',
    professionalId: 'prof-1',
    professionalName: 'Dra. Carolina Castro',
    date: '2025-01-16',
    category: 'Fisioterapia',
    modelTitle: 'Avaliação Ortopédica de Joelho e Membro Inferior',
    chiefComplaint: 'Dor moderada em face anterior do joelho direito e instabilidade percebida ao descer escadas.',
    historyOfPresentIllness: 'Paciente sofreu entorse durante jogo de futebol em 10/10/2024. Submetido a reconstrução ligamentar por artroscopia com enxerto patelar. Apresenta edema residual leve +/4+ e perda de 10 graus de extensão terminal.',
    posturalAssessment: 'Leve valgismo dinâmico em MID durante apoio unipodal. Pelve neutra.',
    painScale: 5,
    romAndStrength: 'ADM Joelho D: Flexão 115º, Extensão -10º. Força Quadríceps: Grau 4-. Isquiotibiais: Grau 4.',
    planOfCare: 'Ganho de extensão completa, eletroestimulação (FES) para vasto medial, treino neuromuscular e crioterapia pós-sessão. Frequência 2x/semana.',
    createdAt: '2025-01-16T14:00:00Z',
  },
];

export const INITIAL_EVOLUTIONS: Evolution[] = [
  {
    id: 'evo-1',
    tenantId: 'tenant-1',
    patientId: 'patient-1',
    professionalId: 'prof-1',
    professionalName: 'Dra. Carolina Castro',
    professionalRegistration: 'CREFITO-3/294819-F',
    date: formatDate(-2),
    time: '09:45',
    procedurePerformed: 'Fisioterapia Traumato-Ortopédica (Joelho D)',
    subjectiveFeedback: 'Paciente relata diminuição das dores ao caminhar no plano. Refere ligeiro cansaço muscular pós-treino domiciliar.',
    objectiveFindings: 'Realizada mobilização patelar grau III, fortalecimento em cadeia cinética fechada (leg press 45º com 20kg), agachamento bipodal em plano instável (Bosu) e treino de marcha com feedback visual. ADM: Flexão 130º / Extensão completa.',
    complicationsOrNotes: 'Sem sinais flogísticos ou dor residual pós-condutas.',
    signature: {
      type: 'drawn',
      dataUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="200" height="50"><path d="M 10 35 Q 50 10 90 35 T 180 30" stroke="%230d9488" stroke-width="2" fill="none"/></svg>',
      signedByName: 'Dra. Carolina Castro',
      signedByRole: 'Fisioterapeuta Responsável',
      registrationNumber: 'CREFITO-3/294819-F',
      timestamp: `${formatDate(-2)} 09:50:12`,
    },
    createdAt: `${formatDate(-2)}T09:50:00Z`,
  },
];

export const INITIAL_PRESCRIPTIONS: Prescription[] = [
  {
    id: 'presc-1',
    tenantId: 'tenant-1',
    patientId: 'patient-1',
    patientName: 'Lucas Mendes de Almeida',
    professionalId: 'prof-1',
    professionalName: 'Dra. Carolina Castro',
    professionalRegistration: 'CREFITO-3/294819-F',
    date: formatDate(0),
    items: [
      {
        medicationOrExercise: 'Exercício 1: Ponte bipodal com faixa elástica (Mini Band)',
        dosageOrFrequency: '3 séries de 12 repetições - 1x ao dia',
        instructions: 'Manter a contração de glúteos no topo por 3 segundos sem hiperestender a lombar.',
      },
      {
        medicationOrExercise: 'Exercício 2: Agachamento isométrico na parede (Wall Sit)',
        dosageOrFrequency: '3 séries de 30 segundos - 1x ao dia',
        instructions: 'Manter joelhos alinhados com a ponta dos pés em ângulo máximo de 60 graus.',
      },
      {
        medicationOrExercise: 'Crioterapia (Bolsa de Gelo)',
        dosageOrFrequency: '20 minutos após treinos e caminhadas longas',
        instructions: 'Envolver a bolsa em tecido fino para proteger a pele.',
      },
    ],
    generalObservations: 'Em caso de dor aguda superior a 6/10 na escala visual, interromper os exercícios e comunicar a clínica.',
    signature: {
      type: 'drawn',
      dataUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="200" height="50"><path d="M 10 35 Q 50 10 90 35 T 180 30" stroke="%230d9488" stroke-width="2" fill="none"/></svg>',
      signedByName: 'Dra. Carolina Castro',
      signedByRole: 'Fisioterapeuta',
      registrationNumber: 'CREFITO-3/294819-F',
      timestamp: `${formatDate(0)} 10:00:00`,
    },
    createdAt: `${formatDate(0)}T10:00:00Z`,
  },
];

export const INITIAL_CONSENT_TERMS: PatientConsentTerm[] = [
  {
    id: 'tcle-1',
    tenantId: 'tenant-1',
    patientId: 'patient-1',
    patientName: 'Lucas Mendes de Almeida',
    patientCpf: '123.456.789-00',
    patientPhone: '(11) 95555-4444',
    professionalId: 'prof-1',
    professionalName: 'Dra. Carolina Castro',
    professionalRegistration: 'CREFITO-3/294819-F',
    termType: 'physiotherapy',
    title: 'Termo de Consentimento Livre e Esclarecido (TCLE) - Fisioterapia & Reabilitação',
    content: `Eu, Lucas Mendes de Almeida, portador(a) do CPF nº 123.456.789-00, declaro que fui devidamente informado(a) pela Dra. Carolina Castro sobre os objetivos, benefícios, métodos, duração estimada e eventuais desconfortos transitórios decorrentes do plano de tratamento fisioterapêutico proposto na clínica FisioPilates Integrada.

Compreendo que a fisioterapia visa a restauração funcional, alívio de sintomas dolorosos e melhora da qualidade de vida, dependendo também do meu comprometimento em seguir as orientações domiciliares, ergonomia e comparecimento às sessões agendadas.

Fui informado(a) de que posso esclarecer dúvidas a qualquer momento do tratamento e que tenho liberdade para revogar este consentimento caso deseje suspender o acompanhamento.`,
    clauses: [
      {
        id: 'c1',
        title: 'Compreensão do Diagnóstico Cinesiológico-Funcional',
        description: 'Fui informado(a) sobre a condição física atual e as condutas terapêuticas indicadas.',
        required: true,
        agreed: true,
      },
      {
        id: 'c2',
        title: 'Ciência sobre Desconfortos Musculares Transitórios',
        description: 'Estou ciente de que dores musculares tardias ou desconfortos leves podem ocorrer após mobilizações e exercícios.',
        required: true,
        agreed: true,
      },
      {
        id: 'c3',
        title: 'Compromisso com o Plano Terapêutico e Orientações',
        description: 'Comprometo-me a seguir os cuidados posturais, exercícios domiciliares e frequência prescrita.',
        required: true,
        agreed: true,
      },
      {
        id: 'c4',
        title: 'Comunicação Imediata de Sintomas Incomuns',
        description: 'Concordo em comunicar imediatamente ao profissional qualquer sensação atípica ou alteração do quadro.',
        required: true,
        agreed: true,
      },
    ],
    patientSignature: {
      type: 'drawn',
      dataUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="240" height="60"><path d="M 15 45 Q 40 15 80 40 T 160 30 T 220 45" stroke="%231e3a8a" stroke-width="2.8" fill="none" stroke-linecap="round"/></svg>',
      signedByName: 'Lucas Mendes de Almeida',
      signedByCpf: '123.456.789-00',
      timestamp: `${formatDate(-5)} às 14:22:10`,
      deviceInfo: 'Dispositivo Touchscreen / Tablet iPad Air',
      verificationHash: 'CFP-TCLE-2025-A8F4E290',
      ipOrLocation: 'Ambiente Clínico Seguro',
    },
    professionalSignature: {
      type: 'drawn',
      dataUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="200" height="50"><path d="M 10 35 Q 50 10 90 35 T 180 30" stroke="%230d9488" stroke-width="2" fill="none"/></svg>',
      signedByName: 'Dra. Carolina Castro',
      signedByRole: 'Fisioterapeuta Responsável',
      registrationNumber: 'CREFITO-3/294819-F',
      timestamp: `${formatDate(-5)} às 14:23:05`,
    },
    status: 'signed',
    signedAt: `${formatDate(-5)}T14:22:10Z`,
    createdAt: `${formatDate(-5)}T14:20:00Z`,
  },
  {
    id: 'tcle-2',
    tenantId: 'tenant-1',
    patientId: 'patient-1',
    patientName: 'Lucas Mendes de Almeida',
    patientCpf: '123.456.789-00',
    patientPhone: '(11) 95555-4444',
    professionalId: 'prof-1',
    professionalName: 'Dra. Carolina Castro',
    professionalRegistration: 'CREFITO-3/294819-F',
    termType: 'lgpd_privacy',
    title: 'Termo de Consentimento para Tratamento de Dados Pessoais e de Saúde (LGPD)',
    content: `Em conformidade com a Lei Geral de Proteção de Dados Pessoais (Lei nº 13.709/2018 - LGPD), eu, Lucas Mendes de Almeida, CPF 123.456.789-00, consinto livremente que a clínica FisioPilates Integrada colete, armazene e processe meus dados pessoais e dados pessoais sensíveis de saúde para as finalidades de guarda do prontuário eletrônico e lembretes de consultas.`,
    clauses: [
      {
        id: 'lgpd1',
        title: 'Guarda Segura de Prontuários e Sigilo Profissional',
        description: 'Autorizo a guarda segura de meus registros clínicos sob sigilo e confidencialidade ética.',
        required: true,
        agreed: true,
      },
      {
        id: 'lgpd2',
        title: 'Envio de Lembretes e Mensagens de Agendamento',
        description: 'Autorizo o envio de lembretes automáticos de consulta e orientações via WhatsApp ou E-mail.',
        required: true,
        agreed: true,
      },
    ],
    patientSignature: {
      type: 'drawn',
      dataUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="240" height="60"><path d="M 15 45 Q 40 15 80 40 T 160 30 T 220 45" stroke="%231e3a8a" stroke-width="2.8" fill="none" stroke-linecap="round"/></svg>',
      signedByName: 'Lucas Mendes de Almeida',
      signedByCpf: '123.456.789-00',
      timestamp: `${formatDate(-5)} às 14:25:00`,
      deviceInfo: 'Dispositivo Touchscreen / Tablet iPad Air',
      verificationHash: 'CFP-TCLE-2025-C3D9911B',
      ipOrLocation: 'Ambiente Clínico Seguro',
    },
    professionalSignature: {
      type: 'drawn',
      dataUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="200" height="50"><path d="M 10 35 Q 50 10 90 35 T 180 30" stroke="%230d9488" stroke-width="2" fill="none"/></svg>',
      signedByName: 'Dra. Carolina Castro',
      signedByRole: 'Fisioterapeuta Responsável',
      registrationNumber: 'CREFITO-3/294819-F',
      timestamp: `${formatDate(-5)} às 14:25:30`,
    },
    status: 'signed',
    signedAt: `${formatDate(-5)}T14:25:00Z`,
    createdAt: `${formatDate(-5)}T14:20:00Z`,
  },
];

export const INITIAL_PACKAGES: Package[] = [
  {
    id: 'pkg-1',
    tenantId: 'tenant-1',
    name: 'Plano Pilates Clínico Mensal (2x/semana - 8 sessões)',
    specialtyId: 'spec-2',
    totalSessions: 8,
    price: 480.0,
    validityDays: 35,
    autoRenew: true,
    active: true,
  },
  {
    id: 'pkg-2',
    tenantId: 'tenant-1',
    name: 'Pacote Reabilitação Ortopédica Intensiva (10 sessões)',
    specialtyId: 'spec-1',
    totalSessions: 10,
    price: 1350.0,
    validityDays: 60,
    autoRenew: false,
    active: true,
  },
  {
    id: 'pkg-3',
    tenantId: 'tenant-1',
    name: 'Pacote Fisioterapia Pélvica & Gestante (5 sessões)',
    specialtyId: 'spec-3',
    totalSessions: 5,
    price: 950.0,
    validityDays: 45,
    autoRenew: false,
    active: true,
  },
];

export const INITIAL_PATIENT_PACKAGES: PatientPackagePurchase[] = [
  {
    id: 'ppkg-1',
    tenantId: 'tenant-1',
    patientId: 'patient-1',
    packageId: 'pkg-2',
    packageName: 'Pacote Reabilitação Ortopédica Intensiva (10 sessões)',
    totalSessions: 10,
    usedSessions: 6,
    purchaseDate: '2025-01-15',
    expirationDate: formatDate(25),
    status: 'active',
    pricePaid: 1350.0,
  },
  {
    id: 'ppkg-2',
    tenantId: 'tenant-1',
    patientId: 'patient-4',
    packageId: 'pkg-1',
    packageName: 'Plano Pilates Clínico Mensal (2x/semana - 8 sessões)',
    totalSessions: 8,
    usedSessions: 7,
    purchaseDate: '2025-02-01',
    expirationDate: formatDate(5),
    status: 'active',
    pricePaid: 480.0,
  },
];

export const INITIAL_ACCOUNTS: Account[] = [
  {
    id: 'acc-1',
    tenantId: 'tenant-1',
    name: 'Banco Itaú - Conta Corrente Principal',
    bankName: 'Banco Itaú',
    accountType: 'checking',
    initialBalance: 15400.0,
    currentBalance: 32850.0,
    active: true,
  },
  {
    id: 'acc-2',
    tenantId: 'tenant-1',
    name: 'Caixa Físico / Recepção',
    bankName: 'Tesouraria',
    accountType: 'cash',
    initialBalance: 500.0,
    currentBalance: 1240.0,
    active: true,
  },
];

export const INITIAL_COST_CENTERS: CostCenter[] = [
  { id: 'cc-1', tenantId: 'tenant-1', name: 'Atendimento Clínico & Sessões', code: 'CC-01', active: true },
  { id: 'cc-2', tenantId: 'tenant-1', name: 'Administrativo & Recepção', code: 'CC-02', active: true },
  { id: 'cc-3', tenantId: 'tenant-1', name: 'Infraestrutura & Manutenção', code: 'CC-03', active: true },
];

export const INITIAL_FINANCIAL_CATEGORIES: FinancialCategory[] = [
  { id: 'cat-1', tenantId: 'tenant-1', name: 'Receita de Sessões Avulsas', type: 'income', color: '#10b981', active: true },
  { id: 'cat-2', tenantId: 'tenant-1', name: 'Receita de Pacotes & Mensalidades', type: 'income', color: '#059669', active: true },
  { id: 'cat-3', tenantId: 'tenant-1', name: 'Repasses & Comissões Profissionais', type: 'expense', color: '#f59e0b', active: true },
  { id: 'cat-4', tenantId: 'tenant-1', name: 'Aluguel & Condomínio', type: 'expense', color: '#ef4444', active: true },
  { id: 'cat-5', tenantId: 'tenant-1', name: 'Materiais Clínicos & Insumos', type: 'expense', color: '#f97316', active: true },
];

export const INITIAL_PAYMENT_METHODS: PaymentMethod[] = [
  { id: 'pm-1', tenantId: 'tenant-1', name: 'PIX Instantâneo', defaultDiscountPercent: 5, taxRatePercent: 0, active: true },
  { id: 'pm-2', tenantId: 'tenant-1', name: 'Cartão de Crédito (1x a 6x)', taxRatePercent: 2.9, active: true },
  { id: 'pm-3', tenantId: 'tenant-1', name: 'Cartão de Débito', taxRatePercent: 1.2, active: true },
  { id: 'pm-4', tenantId: 'tenant-1', name: 'Boleto Bancário (Focus/BoletoSimples)', taxRatePercent: 0, active: true },
  { id: 'pm-5', tenantId: 'tenant-1', name: 'Dinheiro em Espécie', defaultDiscountPercent: 5, active: true },
];

export const INITIAL_FINANCIAL_ENTRIES: FinancialEntry[] = [
  {
    id: 'fin-1',
    tenantId: 'tenant-1',
    type: 'income',
    description: 'Pacote Reabilitação Ortopédica (10x) - Lucas Mendes',
    amount: 1350.0,
    dueDate: formatDate(-15),
    paymentDate: formatDate(-15),
    status: 'paid',
    accountId: 'acc-1',
    accountName: 'Banco Itaú - Conta Corrente Principal',
    categoryId: 'cat-2',
    categoryName: 'Receita de Pacotes & Mensalidades',
    costCenterId: 'cc-1',
    costCenterName: 'Atendimento Clínico & Sessões',
    paymentMethodId: 'pm-1',
    paymentMethodName: 'PIX Instantâneo',
    patientId: 'patient-1',
    patientName: 'Lucas Mendes de Almeida',
    professionalId: 'prof-1',
    professionalName: 'Dra. Carolina Castro',
  },
  {
    id: 'fin-2',
    tenantId: 'tenant-1',
    type: 'income',
    description: 'Mensalidade Pilates Clínico - Juliana Paes',
    amount: 480.0,
    dueDate: formatDate(-5),
    paymentDate: formatDate(-5),
    status: 'paid',
    accountId: 'acc-1',
    accountName: 'Banco Itaú - Conta Corrente Principal',
    categoryId: 'cat-2',
    categoryName: 'Receita de Pacotes & Mensalidades',
    costCenterId: 'cc-1',
    costCenterName: 'Atendimento Clínico & Sessões',
    paymentMethodId: 'pm-2',
    paymentMethodName: 'Cartão de Crédito',
    patientId: 'patient-4',
    patientName: 'Juliana Paes de Barros',
    professionalId: 'prof-1',
    professionalName: 'Dra. Carolina Castro',
  },
  {
    id: 'fin-3',
    tenantId: 'tenant-1',
    type: 'expense',
    description: 'Repasse Quinzena 1 - Dra. Carolina Castro (Comissão 50%)',
    amount: 3450.0,
    dueDate: formatDate(-1),
    paymentDate: formatDate(-1),
    status: 'paid',
    accountId: 'acc-1',
    accountName: 'Banco Itaú - Conta Corrente Principal',
    categoryId: 'cat-3',
    categoryName: 'Repasses & Comissões Profissionais',
    costCenterId: 'cc-1',
    costCenterName: 'Atendimento Clínico & Sessões',
    paymentMethodId: 'pm-1',
    paymentMethodName: 'PIX Instantâneo',
    professionalId: 'prof-1',
    professionalName: 'Dra. Carolina Castro',
  },
  {
    id: 'fin-4',
    tenantId: 'tenant-1',
    type: 'expense',
    description: 'Aluguel do Conjunto Comercial Av. Paulista',
    amount: 4200.0,
    dueDate: formatDate(5),
    status: 'pending',
    accountId: 'acc-1',
    accountName: 'Banco Itaú - Conta Corrente Principal',
    categoryId: 'cat-4',
    categoryName: 'Aluguel & Condomínio',
    costCenterId: 'cc-3',
    costCenterName: 'Infraestrutura & Manutenção',
    paymentMethodId: 'pm-4',
    paymentMethodName: 'Boleto Bancário',
  },
  {
    id: 'fin-5',
    tenantId: 'tenant-1',
    type: 'income',
    description: 'Consulta Fisioterapia Pélvica - Camila Rocha',
    amount: 220.0,
    dueDate: formatDate(0),
    paymentDate: formatDate(0),
    status: 'paid',
    accountId: 'acc-1',
    accountName: 'Banco Itaú - Conta Corrente Principal',
    categoryId: 'cat-1',
    categoryName: 'Receita de Sessões Avulsas',
    costCenterId: 'cc-1',
    costCenterName: 'Atendimento Clínico & Sessões',
    paymentMethodId: 'pm-1',
    paymentMethodName: 'PIX Instantâneo',
    patientId: 'patient-2',
    patientName: 'Camila Rocha Nogueira',
    professionalId: 'prof-3',
    professionalName: 'Dra. Juliana Vasconcelos',
  },
];

export const INITIAL_EQUIPMENT: Equipment[] = [
  {
    id: 'eq-1',
    tenantId: 'tenant-1',
    name: 'Reformer Pilates com Torre e Caixa',
    brand: 'Kauffer Pilates',
    model: 'Classic Wood Pro',
    serialNumber: 'KF-2023-8941',
    acquisitionDate: '2023-04-10',
    lastMaintenanceDate: '2025-01-10',
    nextMaintenanceDate: '2025-07-10',
    roomId: 'room-1',
    status: 'operational',
    active: true,
  },
  {
    id: 'eq-2',
    tenantId: 'tenant-1',
    name: 'Cadillac Trapeze Table',
    brand: 'Metalife',
    model: 'Studio Elite',
    serialNumber: 'ML-99238',
    acquisitionDate: '2022-08-15',
    lastMaintenanceDate: '2024-11-20',
    nextMaintenanceDate: '2025-05-20',
    roomId: 'room-1',
    status: 'operational',
    active: true,
  },
  {
    id: 'eq-3',
    tenantId: 'tenant-1',
    name: 'Aparelho de Laserterapia de Baixa Potência',
    brand: 'DMC',
    model: 'Therapy EC 660nm/808nm',
    serialNumber: 'DMC-44519',
    acquisitionDate: '2023-11-05',
    lastMaintenanceDate: '2025-01-20',
    nextMaintenanceDate: '2026-01-20',
    roomId: 'room-2',
    status: 'operational',
    active: true,
  },
  {
    id: 'eq-4',
    tenantId: 'tenant-1',
    name: 'Equipamento Eletroestimulador Neurodyn Multi-correntes',
    brand: 'Ibramed',
    model: 'Neurodyn Aussie/Russa/TENS',
    serialNumber: 'IBR-77120',
    acquisitionDate: '2022-03-12',
    lastMaintenanceDate: '2024-10-15',
    nextMaintenanceDate: '2025-04-15',
    roomId: 'room-2',
    status: 'maintenance',
    notes: 'Enviado para troca de cabo do canal 3.',
    active: true,
  },
];

export const INITIAL_TECHNICAL_ASSISTANCE: TechnicalAssistance[] = [
  {
    id: 'ta-1',
    tenantId: 'tenant-1',
    equipmentId: 'eq-4',
    equipmentName: 'Equipamento Eletroestimulador Neurodyn',
    orderNumber: 'OS-2025-0042',
    sentDate: formatDate(-5),
    expectedReturnDate: formatDate(7),
    defectDescription: 'Mau contato na saída do canal 3 de estimulação e calibração de rotina',
    repairLocation: 'Assistência Técnica Autorizada Ibramed SP',
    cost: 380.0,
    status: 'in_repair',
  },
];

export const INITIAL_PRODUCT_CATEGORIES: ProductCategory[] = [
  { id: 'pcat-1', tenantId: 'tenant-1', name: 'Insumos de Eletroterapia & Fisioterapia', active: true },
  { id: 'pcat-2', tenantId: 'tenant-1', name: 'Óleos & Cosméticos de Massoterapia', active: true },
  { id: 'pcat-3', tenantId: 'tenant-1', name: 'Acessórios de Pilates & Bandas Elásticas', active: true },
];

export const INITIAL_UNITS: UnitOfMeasure[] = [
  { id: 'u-1', tenantId: 'tenant-1', name: 'Unidade', symbol: 'un', active: true },
  { id: 'u-2', tenantId: 'tenant-1', name: 'Mililitro', symbol: 'ml', active: true },
  { id: 'u-3', tenantId: 'tenant-1', name: 'Pacote / Caixa', symbol: 'cx', active: true },
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-1',
    tenantId: 'tenant-1',
    corporateName: 'MedFisio Distribuidora de Produtos Médicos Ltda',
    tradeName: 'MedFisio Brasil',
    cnpj: '03.888.999/0001-44',
    contactName: 'Carlos Eduardo',
    email: 'vendas@medfisio.com.br',
    phone: '(11) 3210-9800',
    address: 'Rua Vergueiro, 2500 - Vila Mariana - SP',
    suppliedProductsDescription: 'Eletrodos, géis condutores, faixas elásticas e agulhas de agulhamento a seco',
    active: true,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    tenantId: 'tenant-1',
    name: 'Eletrodos Autoadesivos 5x5cm (Pacote com 4 un)',
    code: 'ELET-5050',
    categoryId: 'pcat-1',
    unitOfMeasureId: 'u-3',
    costPrice: 18.0,
    salePrice: 35.0,
    currentStock: 24,
    minStock: 10,
    supplierId: 'sup-1',
    active: true,
  },
  {
    id: 'prod-2',
    tenantId: 'tenant-1',
    name: 'Gel Condutor Incolor para Ultrassom e Eletro (5kg)',
    code: 'GEL-5KG',
    categoryId: 'pcat-1',
    unitOfMeasureId: 'u-1',
    costPrice: 42.0,
    salePrice: 0.0, // Uso interno
    currentStock: 3,
    minStock: 2,
    supplierId: 'sup-1',
    active: true,
  },
  {
    id: 'prod-3',
    tenantId: 'tenant-1',
    name: 'Faixa Elástica TheraBand Nível Médio (Verde)',
    code: 'TB-GREEN',
    categoryId: 'pcat-3',
    unitOfMeasureId: 'u-1',
    costPrice: 28.0,
    salePrice: 55.0,
    currentStock: 5,
    minStock: 6, // Below minimum to trigger alert
    supplierId: 'sup-1',
    active: true,
  },
];

export const INITIAL_MESSAGES: InternalMessage[] = [
  {
    id: 'msg-1',
    tenantId: 'tenant-1',
    senderId: 'user-sec-1',
    senderName: 'Mariana Duarte (Recepção)',
    senderRole: 'secretary',
    recipientId: 'user-prof-1',
    recipientRole: 'professional',
    content: 'Dra. Carolina, o paciente Lucas Mendes já chegou na recepção e aguarda para a sessão das 09:00.',
    timestamp: `${formatDate(0)} 08:55`,
    read: false,
  },
  {
    id: 'msg-2',
    tenantId: 'tenant-1',
    senderId: 'user-prof-1',
    senderName: 'Dra. Carolina Castro',
    senderRole: 'professional',
    recipientId: 'user-sec-1',
    recipientRole: 'secretary',
    content: 'Obrigada Mariana! Já estou finalizando a higienização da sala e o chamarei em 2 minutos.',
    timestamp: `${formatDate(0)} 08:57`,
    read: true,
  },
  {
    id: 'msg-3',
    senderId: 'user-superadmin',
    senderName: 'Equipe ClinicFlow Pro',
    senderRole: 'superadmin',
    recipientId: 'all',
    content: 'Novidade: Nova funcionalidade de exportação de prontuários em formato Paisagem e Retrato já está disponível para todas as clínicas!',
    timestamp: `${formatDate(-3)} 14:00`,
    read: true,
  },
];

export const INITIAL_LICENSES: LicenseKey[] = [
  {
    id: 'lic-1',
    key: 'CFP-EQU-89A4B2-7C1F',
    tenantId: 'tenant-1',
    tenantName: 'FisioPilates Integrada - Clínica São Paulo',
    planId: 'equipe',
    startDate: '2025-01-10',
    expirationDate: '2026-01-10',
    active: true,
    generatedBy: 'SuperAdmin Master',
    hash: 'sha256_mock_fisiopilates_equipe_active',
  },
  {
    id: 'lic-2',
    key: 'CFP-CLI-90FC4E-88D2',
    tenantId: 'tenant-2',
    tenantName: 'Clínica Estética & Bem-Estar BellaCorpo',
    planId: 'clinica',
    startDate: '2025-02-01',
    expirationDate: '2026-02-01',
    active: true,
    generatedBy: 'SuperAdmin Master',
    hash: 'sha256_mock_bellacorpo_clinica_active',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    tenantId: 'tenant-1',
    userId: 'user-admin-1',
    userName: 'Dra. Helena Ribeiro',
    userRole: 'admin',
    action: 'LOGIN_SUCCESS',
    module: 'Autenticação',
    ipAddress: '189.40.12.85',
    device: 'Chrome 122 / MacOS',
    details: 'Login autenticado com sucesso no tenant FisioPilates SP',
    timestamp: `${formatDate(0)} 08:15:30`,
  },
  {
    id: 'log-2',
    tenantId: 'tenant-1',
    userId: 'user-prof-1',
    userName: 'Dra. Carolina Castro',
    userRole: 'professional',
    action: 'EVOLUTION_SIGNATURE_CREATED',
    module: 'Prontuário Eletrônico',
    ipAddress: '189.40.12.85',
    device: 'iPad Safari / iPadOS',
    details: 'Assinatura digital inserida na evolução do paciente Lucas Mendes',
    timestamp: `${formatDate(-2)} 09:50:12`,
  },
  {
    id: 'log-3',
    tenantId: 'tenant-1',
    userId: 'user-sec-1',
    userName: 'Mariana Duarte',
    userRole: 'secretary',
    action: 'APPOINTMENT_CREATED',
    module: 'Agendamentos',
    ipAddress: '189.40.12.85',
    device: 'Windows 11 / Edge',
    details: 'Novo agendamento criado para Camila Rocha Nogueira em 10:30',
    timestamp: `${formatDate(-1)} 16:30:00`,
  },
];

export const INITIAL_HEALTH_INSURANCES: HealthInsurance[] = [
  {
    id: 'conv-1',
    tenantId: 'tenant-1',
    name: 'Unimed Nacional',
    planType: 'ambulatorial',
    typeName: 'Plano Básico & Especial',
    ansCode: '005711',
    phone: '0800 014 5555',
    email: 'autorizacoes@unimed.coop.br',
    coverageDetails: 'Cobre Fisioterapia Geral, RPG e Pilates Clínico mediante guia autorizada.',
    discountPercent: 0,
    requiresAuthorizationGuide: true,
    active: true,
  },
  {
    id: 'conv-2',
    tenantId: 'tenant-1',
    name: 'Bradesco Saúde',
    planType: 'hospitalar',
    typeName: 'Top Nacional & Premium',
    ansCode: '005711',
    phone: '4004-2700',
    email: 'tiss@bradescosaude.com.br',
    coverageDetails: 'Reembolso e faturamento direto com tabela TISS.',
    discountPercent: 10,
    requiresAuthorizationGuide: true,
    active: true,
  },
  {
    id: 'conv-3',
    tenantId: 'tenant-1',
    name: 'SulAmérica Saúde',
    planType: 'coparticipacao',
    typeName: 'Especial & Executivo',
    ansCode: '006246',
    phone: '4004-4935',
    email: 'guias@sulamerica.com.br',
    coverageDetails: 'Autorização online via portal prestador.',
    discountPercent: 5,
    requiresAuthorizationGuide: true,
    active: true,
  },
  {
    id: 'conv-4',
    tenantId: 'tenant-1',
    name: 'Amil Assistência Médica',
    planType: 'ambulatorial',
    typeName: 'Amil 500 / 700 Plus',
    ansCode: '326305',
    phone: '3004-1000',
    email: 'credenciados@amil.com.br',
    coverageDetails: 'Cobre sessões com encaminhamento médico ortopédico/reumatológico.',
    discountPercent: 0,
    requiresAuthorizationGuide: true,
    active: true,
  },
  {
    id: 'conv-5',
    tenantId: 'tenant-1',
    name: 'NotreDame Intermédica',
    planType: 'coparticipacao',
    typeName: 'Advance & Premium',
    ansCode: '359017',
    phone: '0800 015 3855',
    email: 'faturamento@gndi.com.br',
    coverageDetails: 'Rede própria e credenciada com coparticipação reduzida.',
    discountPercent: 0,
    requiresAuthorizationGuide: true,
    active: true,
  },
  {
    id: 'conv-6',
    tenantId: 'tenant-1',
    name: 'Porto Seguro Saúde',
    planType: 'ambulatorial',
    typeName: 'Ouro & Prata',
    ansCode: '000582',
    phone: '3366-3003',
    email: 'saude.prestador@portoseguro.com.br',
    coverageDetails: 'Cobertura ambulatorial de cinesioterapia e reabilitação postural.',
    discountPercent: 5,
    requiresAuthorizationGuide: true,
    active: true,
  },
  {
    id: 'conv-7',
    tenantId: 'tenant-1',
    name: 'Particular / Tabela Direta',
    planType: 'particular',
    typeName: 'Atendimento Particular',
    coverageDetails: 'Sem intermediação de operadoras, pagamento direto na recepção.',
    discountPercent: 0,
    requiresAuthorizationGuide: false,
    active: true,
  },
  {
    id: 'conv-8',
    tenantId: 'tenant-1',
    name: 'Cartão de Todos / Social',
    planType: 'outro',
    typeName: 'Desconto Tabela Social',
    phone: '0800 729 2070',
    coverageDetails: 'Desconto de 20% em sessões avulsas mediante apresentação do cartão ativo.',
    discountPercent: 20,
    requiresAuthorizationGuide: false,
    active: true,
  },
  // Tenant 2 defaults (BellaCorpo)
  {
    id: 'conv-9',
    tenantId: 'tenant-2',
    name: 'Particular / Tabela Estética',
    planType: 'particular',
    typeName: 'Tabela BellaCorpo',
    coverageDetails: 'Tratamentos estéticos corporais e faciais avulsos ou pacotes.',
    discountPercent: 0,
    requiresAuthorizationGuide: false,
    active: true,
  },
  {
    id: 'conv-10',
    tenantId: 'tenant-2',
    name: 'Bradesco Saúde',
    planType: 'ambulatorial',
    typeName: 'Top Nacional (Drenagem Pós-Cirúrgica)',
    ansCode: '005711',
    phone: '4004-2700',
    coverageDetails: 'Reembolso para fisioterapia dermatofuncional pós-operatória.',
    discountPercent: 10,
    requiresAuthorizationGuide: true,
    active: true,
  },
  {
    id: 'conv-11',
    tenantId: 'tenant-2',
    name: 'SulAmérica Saúde',
    planType: 'hospitalar',
    typeName: 'Especial (Pós-Operatório)',
    ansCode: '006246',
    coverageDetails: 'Drenagem linfática pós-cirurgia plástica com laudo médico.',
    discountPercent: 0,
    requiresAuthorizationGuide: true,
    active: true,
  },
];

